networks:
  monitoring:

services:
  loki:
    image: grafana/loki:latest
    user: "$UID:$GID"
    ports:
      - "3131:3131"
    restart: unless-stopped
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - ../loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    user: "$UID:$GID"
    environment:
      - GF_SERVER_HTTP_PORT=13000
    ports:
      - "13000:13000"
    volumes:
      - ../grafana/data:/var/lib/grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.36.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    networks:
      - monitoring

volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
